name: 'coverage'
on: push
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Create xml report
            run: |
              pip install coverage
              coverage run -m unittest discover
              coverage xml
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
