name: 'coverage'
on: push
jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
          OS: ubuntu-latest
          PYTHON: '3.11'
        steps:
          - uses: actions/checkout@v4
          - name: Install requirements
            run: pip install -r requirements.txt
          - name: Create xml report
            run: |
              pip install coverage
              coverage run -m unittest discover .
              coverage xml
          - name: Get Cover 
            uses: orgoro/coverage@v3.1
            with:
                coverageFile: coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
